import {StyleSheet} from 'react-native';
import {COLOR, LINEARGRADIENT} from '../../utils/AppConst';

export default StyleSheet.create({
  body: {
    backgroundColor: COLOR.WHITE_0,
    height: '100%',
    width: '100%',
  },
  header: {
    top: 40,
    // backgroundColor: COLOR.BLUE,
    height: 'auto',
    width: '100%',
    alignItems: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  search: {
    backgroundColor: COLOR.WHITE_5,
    width: '95%',
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 16,
    marginVertical: 20,
  },
  title: {
    fontSize: 25,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  contentner: {
    top: 40,
    paddingHorizontal: 20,
  },
  box: {
    marginTop: 10,
    backgroundColor: COLOR.GREEN_0,
    width: 170,
    height: 190,
    borderColor: COLOR.GREEN,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box1: {
    marginTop: 10,
    backgroundColor: COLOR.YELLOW_2,
    width: 170,
    height: 190,
    borderColor: COLOR.YELLOW,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box2: {
    marginTop: 10,
    backgroundColor: COLOR.PINK_0,
    width: 170,
    height: 190,
    borderColor: COLOR.PINK_2,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box3: {
    marginTop: 10,
    backgroundColor: COLOR.VIOLET,
    width: 170,
    height: 190,
    borderColor: COLOR.VIOLET_0,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box4: {
    marginTop: 10,
    backgroundColor: COLOR.YELLOW_2,
    width: 170,
    height: 190,
    borderColor: COLOR.YELLOW_1,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  box5: {
    marginTop: 10,
    backgroundColor: COLOR.BLUE_1,
    width: 170,
    height: 190,
    borderColor: COLOR.BLUE,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  txtSearch: {
    color: COLOR.GRAY_2,
    paddingLeft: 5,
    marginTop: 5,
  },
});
